#input from user
score_eng = float(input('Foundation English :'))
score_bus = float(input('General Business :'))
score_CompSyst = float(input('Introduction to Computer Systems :'))
score_CompPro = float(input('Computer Programming :'))
print('--- Your Score ---')
print(f'Foundation English : {score_eng}')
print(f'General Business : {score_bus}')
print(f'Introduction to Computer Systems : {score_CompSyst}')
print(f'Computer Programming : {score_CompPro}')